name: 'golangci-lint'
description: 'setup golangci-lint'
inputs:
  version:
    description: 'the version of golangci-lint. e.g. 1.50.1'
    required: false
    default: 'latest'
  path:
    description: 'the path to save the binary of golangci-lint'
    required: false
    default: '~/.local/bin'
runs:
  using: 'composite'
  steps:
    - name: Detect the version of golangci-lint
      id: golangci-lint-version
      uses: ./.github/actions/detect-version
      with:
        name: golangci/golangci-lint
        version: ${{ inputs.version }}
    - name: Cache golangci-lint
      id: golangci-lint-cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.path }}/golangci-lint
        key: golangci-lint-${{ runner.os }}-${{ runner.arch }}-${{ steps.golangci-lint-version.outputs.version }}
    - name: Install golangci-lint
      if: steps.golangci-lint-cache.outputs.cache-hit != 'true'
      shell: bash
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ${{ inputs.path }} v${{ steps.golangci-lint-version.outputs.version }}
