name: 'dockle'
description: 'setup dockle'
inputs:
  version:
    description: 'the version of dockle. e.g. 0.4.10'
    required: false
    default: 'latest'
  path:
    description: 'the path to save the binary of dockle'
    required: false
    default: '~/.local/bin'
runs:
  using: 'composite'
  steps:
    - name: Detect the version of dockle
      id: dockle-version
      uses: ./.github/actions/detect-version
      with:
        name: goodwithtech/dockle
        version: ${{ inputs.version }}
    - name: Cache dockle
      id: dockle-cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.path }}/dockle
        key: dockle-${{ runner.os }}-${{ runner.arch }}-${{ steps.dockle-version.outputs.version }}
    - name: Install dockle
      if: steps.dockle-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        VERSION=${{ steps.dockle-version.outputs.version }}
        wget https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.tar.gz
        tar zxvf dockle_${VERSION}_Linux-64bit.tar.gz
        mv dockle ${{ inputs.path }}
