name: 'trivy'
description: 'setup trivy'
inputs:
  version:
    description: 'the version of trivy. e.g. 0.36.1'
    required: false
    default: 'latest'
  path:
    description: 'the path to save the binary of trivy'
    required: false
    default: '~/.local/bin'
  token:
    description: 'the github token to use GitHub API'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Detect the version of trivy
      id: trivy-version
      uses: ./.github/actions/detect-version
      with:
        name: aquasecurity/trivy
        version: ${{ inputs.version }}
        token: ${{ inputs.token }}
    - name: Cache trivy
      id: trivy-cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.path }}/trivy
        key: trivy-${{ runner.os }}-${{ runner.arch }}-${{ steps.trivy-version.outputs.version }}
    - name: Install trivy
      if: steps.trivy-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b ${{ inputs.path }} v${{ steps.trivy-version.outputs.version }}
