name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check Main
    uses: ./.github/workflows/nx-cloud-main.yml
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      parallel-commands: |
        yarn nx-cloud record -- yarn nx workspace-lint
        yarn nx-cloud record -- yarn nx format:check
      parallel-commands-on-agents: |
        yarn nx affected --target=lint --parallel=2
        yarn nx affected --target=test --parallel=2
        yarn nx affected --target=deploy-img --parallel=2
        NX_CLOUD_DISTRIBUTED_EXECUTION=false yarn nx affected --target=version --parallel=2

  check-agents:
    name: Check Agent
    uses: ./.github/workflows/nx-cloud-agents.yml
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      number-of-agents: 2

  deploy:
    name: Deploy Main
    needs: check
    uses: ./.github/workflows/nx-cloud-main.yml
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      parallel-commands-on-agents: |
        NX_CLOUD_DISTRIBUTED_EXECUTION=false yarn nx affected --target=deploy --parallel=2

  deploy-agents:
    name: Deploy Agent
    needs: check
    uses: ./.github/workflows/nx-cloud-agents.yml
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      number-of-agents: 2
